# Generated by scripts/update-formula.sh; do not edit by hand.
class Zap < Formula
  desc "Fast, reliable and memory efficient JavaScript package manager"
  homepage "https://github.com/elbywan/zap"
  version "0.10.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/elbywan/zap/releases/download/v#{version}/zap-aarch64-apple-darwin"
      sha256 "d13fa16ab3b377d0171c43df8deb1cd1199e061171681afae1cd23a9aebd8d2a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/elbywan/zap/releases/download/v#{version}/zap-x86_64-unknown-linux-musl"
      sha256 "b8ea88c13d62f136b43b6983eb559ac32a7aa182ad5e60710eac641be2847d49"
    end
  end

  def install
    bin.install Dir["zap-*"].first => "zap"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zap --version")
  end
end
