# Generated by scripts/update-formula.sh; do not edit by hand.
class Zap < Formula
  desc "Fast, reliable and memory efficient JavaScript package manager"
  homepage "https://github.com/elbywan/zap"
  version "0.10.0"
  license "MIT"

  on_macos do
    # No Intel macOS build: the toolchain (Homebrew's llvm) dropped it, and
    # the release assets do not cover it (see zap#58). Without this, brew
    # rejects the formula on Intel ("Invalid formula") rather than saying
    # the architecture is unsupported.
    depends_on arch: :arm64
    url "https://github.com/elbywan/zap/releases/download/v#{version}/zap-aarch64-apple-darwin"
    sha256 "d13fa16ab3b377d0171c43df8deb1cd1199e061171681afae1cd23a9aebd8d2a"
  end

  on_linux do
    # The release assets only cover x86_64 Linux, and the same validation
    # simulates linux/arm64 (see the mac block above).
    depends_on arch: :x86_64
    url "https://github.com/elbywan/zap/releases/download/v#{version}/zap-x86_64-unknown-linux-musl"
    sha256 "b8ea88c13d62f136b43b6983eb559ac32a7aa182ad5e60710eac641be2847d49"
  end

  def install
    binary = Dir["zap-*"].first
    bin.install binary => "zap"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zap --version")
  end
end
