# Generated by scripts/update-formula.sh; do not edit by hand.
class Zap < Formula
  desc "Fast, reliable and memory efficient JavaScript package manager"
  homepage "https://github.com/elbywan/zap"
  version "0.10.1"
  license "MIT"

  on_macos do
    # No Intel macOS build: the toolchain (Homebrew's llvm) dropped it, and
    # the release assets do not cover it (see zap#58). Without this, brew
    # rejects the formula on Intel ("Invalid formula") rather than saying
    # the architecture is unsupported.
    depends_on arch: :arm64
    url "https://github.com/elbywan/zap/releases/download/v#{version}/zap-aarch64-apple-darwin"
    sha256 "b482cfafda339a53ec72e1ef1d70e04831f9fb43df6435e8cc48364e7245eaad"
  end

  on_linux do
    # The release assets only cover x86_64 Linux, and the same validation
    # simulates linux/arm64 (see the mac block above).
    depends_on arch: :x86_64
    url "https://github.com/elbywan/zap/releases/download/v#{version}/zap-x86_64-unknown-linux-musl"
    sha256 "0a6d7dd4fc446d5b3b5e96dd67f37646bc90b571d4a73a8dce7a996eb1c72c75"
  end

  def install
    binary = Dir["zap-*"].first
    bin.install binary => "zap"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zap --version")
  end
end
