#!/usr/bin/env bash

# Regenerate Formula/zap.rb from the latest zap release.
#
# Run by .github/workflows/update-formula.yml on a schedule and on demand.
# The zap releases API is public, so no cross-repository token is involved:
# this workflow only needs to write to this repository.

set -euo pipefail

REPO="elbywan/zap"
FORMULA="Formula/zap.rb"

release="$(gh api "repos/$REPO/releases/latest")"
tag="$(jq -r .tag_name <<<"$release")"
version="${tag#v}"

# The digest GitHub computes on upload; fall back to hashing the download
# for assets that predate it.
digest() {
  local name="$1" d
  d="$(jq -r --arg n "$name" '.assets[] | select(.name == $n) | .digest // empty' <<<"$release")"
  if [[ -n "$d" ]]; then
    printf '%s\n' "${d#sha256:}"
  else
    curl --fail --location --silent --show-error \
      "https://github.com/$REPO/releases/download/$tag/$name" | sha256sum | cut -d' ' -f1
  fi
}

for name in zap-aarch64-apple-darwin zap-x86_64-unknown-linux-musl; do
  jq -e --arg n "$name" '.assets[] | select(.name == $n)' <<<"$release" >/dev/null ||
    { echo "error: $tag has no $name asset" >&2; exit 1; }
done

darwin_sha="$(digest zap-aarch64-apple-darwin)"
linux_sha="$(digest zap-x86_64-unknown-linux-musl)"

mkdir -p "$(dirname "$FORMULA")"
cat >"$FORMULA" <<EOF
# Generated by scripts/update-formula.sh; do not edit by hand.
class Zap < Formula
  desc "Fast, reliable and memory efficient JavaScript package manager"
  homepage "https://github.com/$REPO"
  version "$version"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/$REPO/releases/download/v#{version}/zap-aarch64-apple-darwin"
      sha256 "$darwin_sha"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/$REPO/releases/download/v#{version}/zap-x86_64-unknown-linux-musl"
      sha256 "$linux_sha"
    end
  end

  def install
    bin.install Dir["zap-*"].first => "zap"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/zap --version")
  end
end
EOF

# git diff does not see a freshly created file (it is untracked), so ask
# for the status instead: empty porcelain output means nothing changed.
if [[ -z "$(git status --porcelain -- "$FORMULA")" ]]; then
  echo "Formula is up to date with $tag."
  exit 0
fi

git add "$FORMULA"
git -c user.name="github-actions[bot]" \
    -c user.email="41898282+github-actions[bot]@users.noreply.github.com" \
    commit -m "zap $version"
git push
echo "Formula updated to $version."
